```{r}
# Screen data

# author: Ian Hussey (ian.hussey@ugent.be)
# license: GPLv3+


# Dependencies ------------------------------------------------------------


library(plyr)
library(tidyverse)
library(data.table)


# Data acquisition and cleaning -------------------------------------------


## Set the working directory
setwd("raw data/")

# Read all files with the .iqdat extension
files <- list.files(pattern = "\\.csv$")  

# Read these files sequentially into a single data frame
input_df <- dplyr::tbl_df(plyr::rbind.fill(lapply(files, data.table::fread, header = TRUE)))  # tbl_df() requires dplyr, rbind.fill() requires plyr, fread requires data.table

```

```{r}

# Make some variable names more transparent
trimmed_df <- 
  input_df %>%
  dplyr::select(subject,
                correct,
                latency,
                blockcode,
                stimulusitem1,
                trialcode,
                response) %>%
  dplyr::rename(participant = subject,
                stimulus = stimulusitem1,
                demographics_item = trialcode,
                task = blockcode,
                accuracy = correct,
                rt = latency)


# complete data per task --------------------------------------------------


## find participants who have data in each task, 
## then for each check if they had data in all the previous tasks
## return those participants who had data in all tasks

##assess what tasks are there - used for the grepl later (as we don't necessarially need to employ all block names)
#tasks <-
#  trimmed_df %>%
#  dplyr::distinct(task)

# no base funciton for mode, so define one
modal_value <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

#separate each tasks and find uniques
demographics <- #start with demographics
  trimmed_df %>%
  dplyr::filter(grepl("demographics", task)) %>%  # filter rows where the block_name includes string
  dplyr::distinct(participant)

categorization <-
  trimmed_df %>%
  dplyr::filter(grepl("categorization", task)) %>%  # filter rows where the block_name includes string
  dplyr::group_by(participant) %>%
  dplyr::summarize(categorization_rows = n()) %>%  # count the number of trials per participant
  dplyr::ungroup() %>%
  dplyr::mutate(modal_categorization_rows = modal_value(categorization_rows)) %>%  # find modal n of trials
  dplyr::rowwise() %>%
  dplyr::filter(categorization_rows == modal_categorization_rows) %>% # if modal n != n then data is missing or participants has duplicate performance.
  dplyr::select(-modal_categorization_rows)

participants_with_full_data <- 
  dplyr::semi_join(demographics, categorization, by = "participant")


# make lists of participants ----------------------------------------------


## produce prolific codes so that participants can be credited or rejected

# 1. prolific codes for participants with complete data so that they can be paid
prolific_codes_for_complete_participants <-
  dplyr::inner_join(trimmed_df, participants_with_full_data, by = "participant") %>%
  dplyr::filter(demographics_item == "ProlificCode") %>%
  dplyr::select(participant, response) %>%
  dplyr::distinct(participant, .keep_all = TRUE) 


# participants to credit
prolific_codes_for_complete_participants %>% readr::write_csv("data/processed data/prolific codes - complete data.csv")

# participant with complete data - i.e., the inclusion list
prolific_codes_for_complete_participants %>% select(participant) %>% readr::write_csv("data/processed data/inclusion list.csv")

# 1.1 N of complete participants
prolific_codes_for_complete_participants %>% dplyr::summarize(participant = n())


# 2. prolific codes for participants with incomplete data so that they can be rejected
prolific_codes_for_incomplete_participants <-
  dplyr::anti_join(trimmed_df, prolific_codes_for_complete_participants, by = "participant") %>%
  dplyr::filter(demographics_item == "ProlificCode") %>%
  dplyr::select(participant, response) %>%
  dplyr::distinct(participant, .keep_all = TRUE) 

prolific_codes_for_incomplete_participants %>% readr::write_csv("data/processed data/prolific codes - incomplete data.csv")

# 2.1 N of incomplete participants
prolific_codes_for_incomplete_participants %>% dplyr::summarize(participant = n())
```
